name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK
      uses: digreatbrian/buildozer-action@v2
      with:
        buildozer_version: stable
